export const tallyNumbers = {
  "crabvel-tally": 14,
  "fjook_enterprises-tally":	1,
  "luckyparadox-tally": 5,
  "marlo_notfound-tally": 2,
  "moonstruckdragon-tally":	41,
  "nadeenthespore-tally":	118,
  "nel_avhsi-tally":	8,
  "omninboptimist-tally":	14,
  "sintheoracle-tally":	33,
  "stay_big_babe-tally":	1,
  "stinabug_-tally":	2,
  "bitterbonbon-tally":	25,
  "libisaurus-tally":	8,
  "princesajuno-tally":	47,
  "purpleduck1400-tally":	1,
  "tea_flavored_roses-tally":	1,
  "yurt_gurt-tally": 5,
  "khaztaroth315":999,
}